apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-deployment
  name: api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api
  type: NodePort
status:
  loadBalancer: {}
