apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: game-deployment
  name: game
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: game-deployment
  type: NodePort
status:
  loadBalancer: {}
